name: Pack Conda Environment

on:
  push:
    branches:
      - main  # adjust with your primary branch
  workflow_dispatch:
  
jobs:
  conda-pack:
    runs-on: windows-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: "latest"
        activate-environment: myenv

    - name: Create and activate environment
      run: |
        conda env create -n imswitch python=3.9
        conda activate imswitch
        pip install . 
        
    - name: Install conda-pack
      run: conda install -c conda-forge conda-pack

    - name: Conda pack environment
      run: |
        conda pack -n imswitch -o imswitch.tar.gz

    - name: Upload packed environment
      uses: actions/upload-artifact@v2
      with:
        name: packed-env
        path: imswitch.tar.gz
